### ISSUE TITLE
Recurring issue: Meeting agenda and notes

### ISSUE THREAD

**Issue by snairdesai** [snairdesai/MeridianCollective#5]
### Purpose

---

The purpose of this issue (#5) is to document agendas and goals for our weekly meetings moving forward -- this thread will be updated each week by @snairdesai with the following:

**(1):** A brief list of proposed agenda items for each week's meeting, updated in the thread.
**(2):** A brief list of proposed deliverables/goals for the week, if applicable.

Anyone should feel free to edit these as useful. 

cc @nkc98 @haileyrobertson @s-dasaraju @knambiar007 

### Weekly Meeting Notes

---

**You can find a document with our weekly meeting notes [here](https://docs.google.com/document/d/1Lf9nLZjiu-btWQdGyqJ8_hL-r0smYCoDyrxjphkuUyc/edit#), in the shared Google Drive.** We will rotate assignments of who takes notes, conditional on attendees.

**Comment by snairdesai** [comment]
### Weekly Agenda and Goals for Week of 12/05/2022 - 12/11/2022:

**TBC**

**Comment by snairdesai** [comment]
@nkc98 @s-dasaraju @knambiar007 @haileyrobertson Unrelated, but seems our SSRN submission was approved and is now live! You can find it here[here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4283349) .

**Comment by snairdesai** [comment]
### Discussion of Research Ideas (Deliverables for Week of 1/16/2023 - 1/23/2023):

_Rough_ meeting notes from today. @knambiar007 @nkc98 feel free to make any edits if I missed/misinterpreted something.

_KN:_
- Critical refugees course
     - Redefining common terms (diaspora; memory; silence).
     - Sociological/ethnological approaches, very theoretical in nature.
     - Thinking through the space of transit --> how does the act of being stateless during this transit impact you're political and social rights?
     - The idea of _statelessness_ has come up repeatedly, is this possible in a globalized society?
     - Climate refugee situation --> individuals with this status do not have refugee status; there is a moral consideration.
     - KN had started writing an interesting piece with Renee on how extreme weather events affected access to dialysis centers.
     - Unrelated --> how do we deal with the COIs and relationship-based approaches of data/indicator constructions? Maybe this is a perspective piece we can write while we come up with a more fleshed out research idea. 

_NKC:_
- What determines technology transfer within climate spaces? Specifically, how does green industrialization take place?
     - Odd question, because China and other outliers warp our understanding of this concept.
     - Could look at large-scale weather events' on internal migration in the US, or some other setting.

_SND_: Next steps:
- Each of us can try to come up with 1-2 research ideas or designs.
- We can think about a particular setting/policy related to climate risk/refugee status changes/extreme weather outcomes.

**Comment by snairdesai** [comment]
### Discussion of Research Ideas (Deliverables for Week of 1/22/2023 - 1/29/2023):

_Rough_ meeting notes from today. @haileyrobertson @knambiar007 @nkc98 @s-dasaraju feel free to make any edits if I missed/misinterpreted something.

_HR:_
- Potential datasets to utilize from [WWHGD](https://www.wwhgd.org/).
- Team is working a lot on the ecology piece; could be interesting to look at the intersections between human migration and animal habitats (particularly those who are disease carriers).

_SD:_
- Fan of the research topic [above](https://github.com/snairdesai/MeridianCollective/issues/5#issuecomment-1397789674).
- Unrelated, but we could try to partner with data journalism outlets for the COVID paper.
- The hardest part of the topic we're discussing now is high-quality migration data.
- Maybe we start by looking at internal migration; cross-state migration.

_NKC:_
- Finding country-to-country migration flows might be a little simpler, but finding within-country migration will be hard enough, tying it to climate events seems even more difficult.

_KN:_
- Maybe we could find a particular event study or natural experiment design?
- There's a lot of room for creativity here, because it's such a complex set of questions.
- Could we take a subset of migration policy and examine deterrents.

## Next steps:

Individual tasks and issues to assign throughout the team:

- **(i)** finding a publication home for prior output @knambiar007 
- **(ii)** admin tasks related to website maintenance; social media marketing etc. @haileyrobertson
- **(iii)** immediate next steps for topic of interest; i.e. data search + lit. review. @nkc98 @s-dasaraju @snairdesai 
- **(iv)** generating GitHub issues for all of the above @snairdesai

**Comment by snairdesai** [comment]
### Weekly Agenda and Goals for Week of 1/29/2023 - 2/04/2023:

The purpose this week's meeting (2/2/2023) will be a workshop in pursuit of #8 - sourcing additional literature and data for our climate risk project.

**Comment by snairdesai** [comment]
## Weekly Agenda and Goals for Week of 2/02/2023 - 2/09/2023:

As we did not meet last week, the purpose of this week's meeting is the same as above - a workshop in pursuit of #8 - sourcing additional literature and data for our climate risk project.

**Comment by snairdesai** [comment]
- _KN_:

    - We need an outcome variable of interest. It seems we have two outcomes: exposure to extreme weather events and institutional response. But do we want to focus on the political elements here (perhaps, some legislative documentation of which countries have legal frameworks for climate refugees, etc.)? Or do we focus on the degree of exposure, etc.
    - Maybe we can look at global refugee data (for example recent earthquake data).
    - KN's theoretical interest: our global organizations are failing in disaster relief. Eventually, studying humanitarian aid responses from these IGOs would be very interesting.

- _NC_:

   - Scholars have studied how immigrants have improved total factor productivity, etc. Could do something like this?
   - Two major issues here: (1) internal migration is hard to measure without access to rich administrative data; (2) for global flows of climate migration; the willingness to accept migrants regardless is a confounding feature; and linking international migration to climate events is difficult, because it is less frequent that a climate disaster affects an entire country or region.
   - Theoretical frameworks that are potentially interesting: remittances.
   - In terms of data, using a country time-series level dataset seems the most promising.

**Comment by snairdesai** [comment]
## Weekly Agenda and Goals for Week of 3/05/2023 - 3/11/2023:

As we did not meet last week, the purpose of this week's meeting is the same as [above](https://github.com/snairdesai/MeridianCollective/issues#issuecomment-1414287825) - a workshop session in pursuit of #8 - sourcing additional literature and data for our climate risk project. 

If any of us have had a chance to read through some of the papers linked in #8 on our own time, we can present our findings/summaries to the broader group. 

Feel free to make any suggestions if you wish to alter this agenda!

cc @nkc98 @haileyrobertson @s-dasaraju @knambiar007

**Comment by s-dasaraju** [comment]
## Notes from 3/09/2023 Meeting: Discussion of Papers 

COVID-19 India Migration Paper 
 - paper looks at interstate and intra-state (within India) migration patterns (pre-lockdown vs post-lockdown), states that got ration cards vs states that did not. 
 - method: diff in diff 
 - measuring mobility using FB mobility data

**Comment by snairdesai** [comment]
**CRITICAL/TLDR**

by next weel

- By Monday (3/13) the group will decide on a paper to review for next meeting. All of us should (depending on bandwidth) spend more time on this paper.
    - Ideally, we want the paper to be comparative analysis of costs/benefits of different _datasets_ on internal migration a la [Internal Migration Data Around the World: Assessing Contemporary Practice](https://onlinelibrary.wiley.com/doi/10.1002/psp.1848).


**Would be nice**

- @snairdesai; @nkc98; @haileyrobertson; @knambiar007 to read Sri's paper (3.3 on).
- @snairdesai to make a shared Zotero library where we place the most important papers.
- @s-dasaraju To take a deeper look through the IDMC data with @nkc98 providing any support as possible.
- @knambiar007 To keep group posted on the status of #6.
- @haileyrobertson To continue working through website and ping @snairdesai @s-dasaraju with HTML questions in #7.
    - Per @s-dasaraju: We want to ensure that all of us list any of our active publications on the MC webpage (even those not directly affiliated with MC).
    - Per @snairdesai: At some point, depending on bandwidth, want to shoot a quick 30-second to 1 minute group intro vid. for webpage (low priority)

**Comment by snairdesai** [comment]
@s-dasaraju @haileyrobertson @nkc98 @knambiar007 Porting here from `Slack`: reminder that by **tomorrow** , we want to have decided as a group upon a paper for us to review in advance of next week's meeting (Thursday, 3/16/2023 at 4PM PDT). We can reference #8 as a helpful guide. Feel free to post your ideas here or on `Slack`.

**Comment by snairdesai** [comment]
@s-dasaraju @haileyrobertson @nkc98 @knambiar007: Following up from the task list [above](https://github.com/snairdesai/MeridianCollective/issues/5#issuecomment-1463068916) -- you should have gotten an invite to our group Zotero (`MeridianCollective`) to your emails, let me know if it doesn't come through! We can make a new subfolder for each of our projects.

**Comment by snairdesai** [comment]
## Notes from 3/16/2023 Meeting: Discussion of IDMC Dataset

**Takeaway**: There seem to be a lot of issues with the IDMC data (see this report), and we are a bit concerned about filtering this data down to a single country or timeframe given the caveats required. We discussed whether finding alternative subnational data which proxies for migration outcomes might be more useful (i.e., spatial or text data), where we potentially condition on natural disasters as natural experiments for pre- and post-periods.

_KN:_

- Datasets from HNOs (humanitarian needs organization) available [here](https://data.humdata.org/dataset) --> includes summary of where gaps arise (almost nothing on remedies to justice around housing, etc.).
- If we want to use this we need to be cautious about which indicators we place weight on.
- The reasons for internal migration are not well documented in this dataset, this is more tracking outcomes after the fact.
- OCENT research --> specific human rights violation; use social media as an outlet or proxy.

_SD:_

- Broadly agree with Sameer's comments, but what better data is there for us to begin with?
- Should we start from the data and figure out a question, or start from a research puzzle and try to find data on this?
- Think about the types of papers that we want to produce? Should we just do a meta-analyses ourselves of some niche topic in climate/human rights?
- Lots of papers use natural disasters like tsunamis, earthquakes, etc. --> how does this affect outcomes in conflict?

_Deliverables:_

- Concretely: We want _one person_ to look at data journalism pieces and put together a list of datasets/ideas people are putting out.
- Two people should do literature review on _sub-national data_ on internal migration, with a focus on how they proxy for migration indicators.
- What are geography/spatial sciences journals saying about this? How can we analyze spatial/text data.

**Comment by snairdesai** [comment]
@s-dasaraju @knambiar007 @nkc98 @haileyrobertson You can find the (rough) meeting notes from today [above](https://github.com/snairdesai/MeridianCollective/issues/5#issuecomment-1472905714) -- I'll post a formatted version of these and our deliverables (along with the Zoom transcripts) shortly.

**IMPORTANT**: Discussion on meeting structure moving forward. @s-dasaraju suggested the following meeting structure moving forward, given that it's been difficult for us to find time outside of the meetings to work through lit/data:

We extend length of meeting to an hour and a half, with first 45 minutes dedicated to workshop; and last 45 minutes for discussion. People can opt to join either/both of these sessions depending on availability each week.

What are people's general thoughts on this? Feel free to react with a :thumbsup: or :thumbsdown: emoji, or reply in this thread.

**Comment by snairdesai** [comment]
@s-dasaraju @knambiar007 @nkc98 @haileyrobertson Following up here -- how do people feel about the new meeting structure outlined [above](https://github.com/snairdesai/MeridianCollective/issues/5#issuecomment-1472906953)? If we're good with that, I'll extend the meeting times (starting from the week of 3/30/23).

**Comment by snairdesai** [comment]
## Notes from 3/30/2023 Meeting: Discussion of Other Datasets/Questions of Interest

This week's meeting was mostly a workshop to source data, but Sri had some helpful ideas/sources which I've outlined below.

[**TO POST - Audio Transcript of Meeting**]()

_SD:_

- Found some helpful datasets which will be ported to GitHub shortly.
- Could be interesting to look at state governance responses or insurance markets to high-risk climate environments. 
     - For example, if we look at Native communities (reservations), could we examine federal funding on climate crisis management (forest fires)?
- Are there detectable patterns in how multinational companies are targeting investing flows towards increasingly high-risk climate areas? 
     - We can look at a specific panel of investments for a given region with a recent climate disaster. Here, outcome is investment; exogenous shock/systemic issue is climate disaster, or slow climate burn.
- In terms of regional focus, maybe let's start with the US, and then look at broader global levels. Focusing on native or indigenous communities seems like a good start.

Two sources from Sri:

- [Crowdsources images of climate disasters.](https://www.iseechange.org/projects)
- [Pew Report on Wildfire Management.](https://www.pewtrusts.org/en/research-and-analysis/fact-sheets/2022/11/how-states-can-manage-the-growing-price--of-wildfires)
- [Pew Report on Wildfire Spending.](https://www.pewtrusts.org/en/research-and-analysis/speeches-and-testimony/2023/03/09/pew-recommends-improved-accounting-of-wildfire-spending-and-enhanced-mitigation-efforts)

**Comment by snairdesai** [comment]
## Notes from 4/06/2023 Meeting: Focus on Tribal Reservation data.

This week's meeting was mostly a workshop to source data, but Sri had some helpful ideas/sources which I've outlined.

https://data.gov/climate/tribal-nations/data-page/
https://biamaps.doi.gov/portal/apps/webappviewer/index.html?id=53794ae1ce054029bd5b55bcf269434c
https://www.science.org/doi/10.1126/science.abe4943

<img width="269" alt="Screen Shot 2023-04-06 at 4 59 27 PM" src="https://user-images.githubusercontent.com/63830369/230514407-2a97ed8a-fabf-4452-9c20-925d68a4e0c9.png">

**Comment by snairdesai** [comment]
## Notes from 4/20/2023 Meeting: Honing in on higher-quality spatial data on Tribal Reservations.

I found an interesting source file from the US govt. which, if we can gain access to the underlying data, seems like a very useful start. You can find it [here](https://bia-geospatial-internal.geoplatform.gov/operational/) - it maps real-time climate risks across Tribal Lands, merging data from a large set of other govt. datasets. I'll send an email to the office soon and see if we can gain access. [This dataset](https://data.noaa.gov/onestop/collections/details/efd08cba-0011-49ed-9ae8-4ff58216b91d) on the demographics of these areas also seems useful, but might be private access.

If we gain access to either/both of these spatial datasets, we can potentially merge the following:

- Real-time data from [USGS](https://www.usgs.gov/products/data/real-time-data) on current climate risks.
- Historical data on [irrigated lands](https://www.usgs.gov/data/verified-irrigated-agricultural-lands-united-states-2002-17) and [fish cultures](https://www.usgs.gov/data/ficli-fish-and-climate-change-database-2021-update).
- Projections and historical data on climate risks in tribal communities from the [University of Washington](https://climate.northwestknowledge.net/NWTOOLBOX/tribalProjections.php).
- Real-time drought data from [NIDIS](https://www.drought.gov/tribal) and [UNL](https://droughtmonitor.unl.edu/DmData/TimeSeries.aspx).
- Real-time [community-reported data](https://data.leonetwork.org/) on climate risks.

**Comment by snairdesai** [comment]
### Notes from 5/11/2023 Meeting: Deliverables from team:

----

- Important questions re: linking tribal climate plans to federal/state funding:
          - **(1)** Are the tribal communities at "most risk" based on the climate data we gather getting proportional funding?
          - **(2)** What are the features of the communities most "at risk"?
          - **(3)** What does the text analysis of these climate plans reveal re: standardizing for grants; do they acknowledge disproportionate climate harms more broadly; what type of climate response are these action plans geared towards (i.e. adaptation focused, mitigation focused, etc.).
          - **Deliverable**: Interactive visualization or dashboard which lives online.

- [ ] @snairdesai to email the government GIS providers and post updates in this thread.
- [ ] @s-dasaraju to upload the climate plans in a new issue.

**Comment by snairdesai** [comment]
Closing for now until regroup with **MC**.
