### ISSUE TITLE
Sourcing literature and datasets for climate risk project

### ISSUE THREAD

**Issue by snairdesai** [snairdesai/MeridianCollective#8]
The purpose of this issue (#8) follows from the decisions made at our [weekly meeting on 1/22/2023](https://github.com/snairdesai/MeridianCollective/issues/5#issuecomment-1405870477). We will be proceeding with a preliminary investigation of what is available re: the broad research topics discussed of:

- How has the increasing frequency of extreme weather events has affected patterns of forced migration
- How have vulnerable populations been affected by these events? Specifically, how do they fall through the cracks of political/social institutions (for example, not receiving refugee status for climate disasters)?

Per our conversation, @nkc98 and @s-dasaraju have been assigned as primaries to complete this step, with @snairdesai providing additional support. Of course, @knambiar007 and @haileyrobertson feel free to contribute anything additional as you see fit. 

Any updates relating links to datasets or helpful literature (as well as summaries of these papers in the latter case) can be posted directly in this thread. Ideally we have some initial updates for the team prior to our next meeting on Wednesday, 2/1/2023.

**Comment by knambiar007** [comment]
https://link.springer.com/article/10.1007/s41885-021-00100-8 (Methods for this one is interesting, looking at cold-weather events in Bangladesh and is a population time series 
Our database is a time series of migration and population data at provincial and district level from official population registries, spanning the 1992-2018 period. Results obtained with a two-way fixed effects panel estimator show that extreme winter events cause significant and sizeable permanent out-migration from affected provinces for up to two years after an event.) 

Migration database:  Internal Displacement Monitoring Centre (IDMC) Global Internal Displacement Database (GIDD)
EWE database: Centre for Research on the Epidemiology of Disasters (CRED) Emergency Events Database (EM-DAT).

**Comment by snairdesai** [comment]
Additional datasets from @s-dasaraju:

- [Climate Change Knowledge Portal (World Bank)](https://climateknowledgeportal.worldbank.org/about)
     - The World Bank created the Climate Change Knowledge Portal (CCKP) to serve as a hub for climate-related information, data and tools. The Portal provides an online platform for access to comprehensive global, regional, and country data related to climate change and development. 

- [GIS for Climate HUB (ESRI)](https://climate-arcgis-content.hub.arcgis.com/)
     - Hub of ESRI’s climate-related open data and visualizations. See also ESRI’s [GIS for Climate Change webinars](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fclimate-arcgis-content.hub.arcgis.com.mcas.ms%2F%3FMcasTsid%3D15600&McasCSRF=691d7f837995ce600eaee966a83e7946229111367bd89294379d17f0a43c1714).

- [ND-GAIN Country Index (University of Notre Dame)](https://gain.nd.edu/our-work/country-index/rankings/)
     - The ND-GAIN Country Index summarizes a country’s vulnerability to climate change and other global challenges in combination with its readiness to improve resilience. A country’s ND-GAIN index score is composed of a vulnerability score and a readiness score. 

- [ESRI Total Annual Precipitation Data](https://hub.arcgis.com/maps/a727a4f6d5ab4fc5b1683d32dee45f54/explore?location=6.963250%2C148.496400%2C2.75); [ESRI Drought Data](https://climate-arcgis-content.hub.arcgis.com/search?q=drought); and [ESRI Drought Tracker](https://www.arcgis.com/home/item.html?id=5714b85eb1a341cb8cdf207178449709)

- [MODIS Optical Global Water Intelligence (NGA and Army Corps of Engineers)](https://umip.erdc.dren.mil/apps/dort/)
     - The MODIS Optical Global Water Intelligence (MOGWAI) platform is a near real-time, remote sensing-based lake/reservoir surface area monitoring system created and maintained by the National Geospatial-Intelligence Agency and U.S. Army Corps of Engineers.
     - The surface area estimates are based on an implementation of the Dynamic Surface Water Extent (DSWE) algorithm that was adapted to use 8-day composites of surface reflectance data from NASA’s MODIS (Moderate Resolution Imaging Spectroradiometer) sensor. Surface area is monitored for all large water bodies (>10 km2) south of 60N that are included in the WWF’s HydroLakes database.
     - For more information or to recommend new water bodies for monitoring, please contact [MOGWAI@nga.mil](mailto:MOGWAI@nga.mil). MOGWAI is available via the USACE Model Interface Platform with access available via CAC/PIV or Login [here](https://umip.erdc.dren.mil/apps/dort/).

- [NASA Global Precipitation Measurement Data Directory (NASA)](https://gpm.nasa.gov/data/directory)

- [Global Precipitation Measurement Mission (GPM) (NASA)](https://gpm.nasa.gov/)
     - GPM uses satellites to measure Earth’s rain and snowfall. Launched by NASA and JAXA on Feb. 27th, 2014, GPM is an international mission that sets the standard for spaceborne precipitation measurements. 
     - Using a network of satellites united by the GPM Core Observatory, GPM expands on the legacy of the Tropical Rainfall Measuring Mission (TRMM) by providing high quality estimates of Earth’s rain and snowfall every 30 minutes.

- [IMERG: Integrated Multi-satellitE Retrievals for GPM (NASA)](https://gpm.nasa.gov/data/imerg)
     - There are several sources for downloading and viewing data which allows sub-setting the data to only include specific parameters and/or geographic locations. These include the GES DISC (Giovanni) and STORM. In Giovanni data is available for a specific country, U.S. state, or watershed by using the “Show Shapes” option in the “Select Region” pane.

- [WorldClim Database (WorldClim)](https://worldclim.org/data/index.html)
      - WorldClim is a database of high spatial resolution global weather and climate data. These data can be used for mapping and spatial modeling. The data are provided for use in research and related activities; and some specialized skill and knowledge is needed to use them.

- [Global Food Security Index (The Economist Intelligence Unit)](https://foodsecurityindex.eiu.com/)
     - The Global Food Security Index (GFSI) considers the issues of food affordability, availability, quality and safety, and natural resources and resilience across a set of 113 countries. The index is a dynamic quantitative and qualitative benchmarking model constructed from 59 unique indicators that measure the drivers of food security across both developing and developed countries.

- [World Bank Climate Change Knowledge Portal](https://climateknowledgeportal.worldbank.org/about)
     - The Climate Change Knowledge Portal (CCKP) provides global data on historical and future climate, vulnerabilities, and impacts.

- [GIS for Climate](https://climate-arcgis-content.hub.arcgis.com/)

**Comment by snairdesai** [comment]
We can post any promising datasets in our issue branch [here](https://github.com/snairdesai/MeridianCollective/tree/issue8_data_lit_collection).

**Comment by nkc98** [comment]
https://www.pnas.org/doi/10.1073/pnas.1002632107

**Comment by nkc98** [comment]
From last week: 

- Revised Research Idea: Examine internal climate migration (using [internal migration event-level dataset](https://www.internal-displacement.org/database/displacement-data)) as a causal determinant of socioeconomic outcomes (e.g. climate policy, civil conflict, etc. etc.). 
- Intended approach: Use an instrumental variable approach to establish a semi-causal effect.

**Comment by snairdesai** [comment]
_Additional papers:_

#### Overviews of Literature
- [The Economics of Internal Migration: Advances and Policy Questions](https://www.federalreserve.gov/econres/feds/files/2022003pap.pdf)

#### Methods Related
---
- [Shift-Share Instruments and the Impact of Immigration](https://docs.iza.org/dp11307.pdf)

#### Data Related
- [Internal Migration Data Around the World: Assessing Contemporary Practice](https://onlinelibrary.wiley.com/doi/10.1002/psp.1848)

#### Outcome Related
- [The Labour Market Impacts of Female Internal Migration: Evidence from the End of Apartheid](https://www.sciencedirect.com/science/article/abs/pii/S0166046220303094)

**Comment by knambiar007** [comment]
- [Migration and climate change – The role of social protection](https://www.sciencedirect.com/science/article/pii/S2212096322000791)

[A systematic review of climate migration research: gaps in existing literature](https://link.springer.com/article/10.1007/s43545-022-00341-8)

[Forced displacement and climate change: Time for global governance](https://journals.sagepub.com/doi/pdf/10.1177/0020702020968944?casa_token=UMBq5iohbqQAAAAA:V-AOjjlqSlwCgaH79XcXQiZ4VA989JYkFr7QxQgTgCL2gKFfIFGR9NF4ixZXOaXb2yd-IbR96Kne)

**Comment by nkc98** [comment]
[First Street Foundation Climate Risk Data](https://firststreet.org/data-access/public-access/)

- Looks like they have some sort of public access portal
